stack:

<stack>:

<Interface>:
    # "left", "center", "top"
    achor_x: "center"
    # "top", "center", "bottom"
    achor_y: "center"
    GridLayout:
        cols: 2
        size_hint: .50, .20
        Button:
            text: '1'
            backgroud_color: .2,.3,.7,1
        Button:
            text: '2'
            backgroud_color:  .2,.3,.7,1
        Button:
            text: '3'
            backgroud_color: .2,.3,.7,1
        Button:
            text: '4'
            backgroud_color:  .2,.3,.7,1