<Interface>:
Interface:
    rows: 2
    cols: 2
    #aqui forçamos o programa a definir o tamanho da coluna
    col_force_default: False
    col_default_width: 160
    #aqui forçamos o programa a definir o tamanho da linha
    row_force_default: True
    row_default_height: 40
    spacing: [4, 0]
    #esquerda, topo, direito, baixo
    padding: [40,500,100,0]
    Button:
        text: '1'
        size_hint: None, 1
        size: 100, 1
    Button:
        text: '2'
    Button:
        text: '3'
        size_hint: None, 1
        size: 100, 1
    Button:
        text: '4'